project1/config/routes.rb
Rails.application.routes.draw do
  get 'cates/index'
  resources :products
  resources :categories
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

project1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project1/app/models/category.rb
class Category < ApplicationRecord
  has_many :labels
  has_many :products, through: :labels
  validates :name, length: { minimum: 3 }
end

project1/app/models/label.rb
class Label < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

project1/app/models/product.rb
class Product < ApplicationRecord
  has_many :labels
  has_many :categories, through: :labels
  validates :name, length: { minimum: 3 }
end

project1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

project1/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show

  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

project1/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    # @cate = Category.find_by_id(1).products
    @cate = Category.all
    # @makers = Lable.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @cate = Category.find_or_create_by(id: params[:product][:category_ids])
    respond_to do |format|
      if @product.save
        # @product.categories << @cate
        @product.labels.find_or_create_by(category_id: @cate.id)
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = Product.find_by_id(params[:id]) # tìm @product theo id product
    @cate = Category.find_by_id(params[:product]["category_ids"])  # tìm @cate theo id product.cate , nghĩa là trong product đó có id cate
    @labels = @product.labels.first # tìm @maker trong bảng trung gian có id product , lấy cái đầu tiên
    respond_to do |format|
      if @product.update(product_params)
        @labels.update_attributes(category_id: @cate.id )
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image)
    end
end

project1/app/helpers/application_helper.rb
module ApplicationHelper
end

project1/app/helpers/cates_helper.rb
module CatesHelper
end

project1/app/helpers/products_helper.rb
module ProductsHelper
end

project1/app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project1/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

project1/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

project1/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

project1/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

project1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

project1/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class = "field">
     <%= form.label :'thể loại'%>
     <%= form.collection_select :category_ids , Category.all, :id, :name, promt: 'Thể loại'%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project1/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product, :class =>"btn" %> |
<%= link_to 'Back', products_path, :class =>"btn"  %>
<%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn" %>

project1/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Product', new_product_path, :class => "btn" %>
<h1>Products</h1>

<!-- Area for view Product -->

<!-- End of area for view Product -->
<br>

<!-- Add new Product -->
<% @cate.each do |cate| %>
  <p><%= cate.name %></p>
  <% cate.products.each do |product| %>
    <div class="product-card">
      <%= link_to image_tag(product.image), product%>
      <h4 class="title"><%= product.name%></h4>
    </div>
  <% end %>
<% end %>

project1/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, :class => "btn" %>

project1/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p> -->


<div class="show-product">
  <div class="product-img">
    <%= image_tag(@product.image) %>
  </div>
  <div class="product-info">
    <h2 class="name"><%=@product.name%></h2>
    <p class="description"><%=@product.description%></p>
  </div>
</div>

<%= link_to 'Edit', edit_product_path(@product), :class => "btn"%> |
<%= link_to 'Back', products_path, :class => "btn" %>